//================= Network Configration =======================//
const URIS = {
    DEVELOPMENT: 'http://demo27.iitpl.com/api/',
    PRODUCTION: '',
    STAGING: '',
};

const HTTP_CODES = {
    SUCCESS: 200,
    UNAUTHORIZED: 401,
    VALIDATION: 422,
    SERVER_ERROR: 500,
};

const URI_METHODs = {
    LOGIN: 'login',
    REGISTRATION: 'register',
    MOBILE: 'send-registration-otp',
    OTP_VRIFY: 'register-otp-verify',
    PROFILE: 'profile',
    PLAN: 'packages',
    DASHBOARD_SEARCH: 'home',
    FORGOT_PASSWORD: 'forgot-password',
    FORGOT_OTP_VERIFY: 'verify-forgot-password-otp',
    RESEND_OTP: 'resend-otp',
    RESET_PASSWORD: 'update-password',
    SEND_MEETUP: 'history',
    RECVIED_MEETUP: 'recived-request-history',
    REJECT_MEETUP: 'reject-request',
    RECEIVER_PROFILE: 'user_detail',
    SEND_MEETUP_RECEIVER_PROFILE: 'send-meetup',
    RATING_LIST: 'complete-meetup-rate',
    REFERAL: 'get-referal-code',
    SAVE_RATING: 'submit-meetup-ratting',
    STATIC_PAGE: 'page-content',
    FAQ: 'faq',
    ADD_COIN: 'addcoin',
    CALCULATE_COINS: 'calculate-coins',
    WITHDRAW_COINS: 'withdraw',
    UPDATE_PROFILE: 'update-profile',
    VERIFY_EMAIL: 'verify-email',
    DELETE_ACCOUNT: 'delete-account',
    CONTACT_US: 'submit-contact-us',
    OTP_REAL_MEETUP: 'otp-for-real-meetup',
    CHAT_HISTORY: 'chat-history',
    MEETUP_OTP_CONFIRM: 'complete-meetup',
    RESEND_MEETUP_OTP: 'resend-meetup-otp',
    MEETUP_INTERACTION: 'interaction',
    ACTIVE_CHAT: 'active-chat-list',
    DELETE_CHAT: 'delete-chat',
    ACCEPT_MEETUP: 'accept-request',
    COINS_TRANSFER: 'coin-transfer',    
    CREATEACCOUNT: 'create-account',
    COUNTRY: 'country',
    STATE: 'get-states-by-country',
    CITY: 'get-cities-by-state',
    SOCIALLOGIN: 'google-login',
    NOTIFICATION: 'notification',
    RATINGHISTORY: 'ratting-history',
    ONLINE_OFFLINE: 'online_status',
    CHAT_STATUS: 'user-chat-status',
    CITIES: 'cites',
};

const STATIC_PAGE = {
    PRIVACY_POLICY: '',
    TERMS_CONDITION: '',
};

//================== Font Family =============================//
const FONT_FAMILIES = {
    // ****************Roboto***********************
    ROBOTO_BLACK: 'Roboto-Black',
    ROBOTO_BLACKITALIC: 'Roboto-BlackItalic',
    ROBOTO_BOLD: 'Roboto-Bold',
    ROBOTO_BOLDITALIC: 'Roboto-BoldItalic',
    ROBOTO_ITALIC: 'Roboto-Italic',
    ROBOTO_LIGHT: 'Roboto-Light',
    ROBOTO_LIGHTITALIC: 'Roboto-LightItalic',
    ROBOTO_MEDIUM: 'Roboto-Medium',
    ROBOTO_MEDIUMITALIC: 'Roboto-MediumItalic',
    ROBOTO_REGULAR: 'Roboto-Regular',
    ROBOTO_THIN: 'Roboto-Thin',
    ROBOTO_THINITALIC: 'Roboto-ThinItalic',
    // ****************Inter***********************
    INTER_BLACK: 'Inter-Black',
    INTER_BOLD: 'Inter-Bold',
    INTER_EXTRABOLD: 'Inter-ExtraBold',
    INTER_EXTRALIGHT: 'Inter-ExtraLight',
    INTER_LIGHT: 'Inter-Light',
    INTER_MEDIUM: 'Inter-Medium',
    INTER_REGULAR: 'Inter-Regular',
    INTER_SEMIBOLD: 'Inter-SemiBold',
    INTER_THIN: 'Inter-Thin',
    // ****************Poppins***********************
    POPPINS_BLACK: 'Poppins-Black',
    POPPINS_BLACKITALIC: 'Poppins-BlackItalic',
    POPPINS_BOLD: 'Poppins-Bold',
    POPPINS_BOLDITALIC: 'Poppins-BoldItalic',
    POPPINS_EXTRABOLD: 'Poppins-ExtraBold',
    POPPINS_EXTRABOLDITALIC: 'Poppins-ExtraBoldItalic',
    POPPINS_EXTRALIGHT: 'Poppins-ExtraLight',
    POPPINS_EXTRALIGHTITALIC: 'Poppins-ExtraLightItalic',
    POPPINS_ITALIC: 'Poppins-Italic',
    POPPINS_LIGHT: 'Poppins-Light',
    POPPINS_LIGHTITALIC: 'Poppins-LightItalic',
    POPPINS_MEDIUM: 'Poppins-MediumItalic',
    POPPINS_REGULAR: 'Poppins-Regular',
    POPPINS_SEMIBOLD: 'Poppins-SemiBold',
    POPPINS_THIN: 'Poppins-Thin',
    POPPINS_THINITALIC: 'Poppins-ThinItalic',
    // ****************Montserrat***********************
    MONTSERRAT_BLACK: 'Montserrat-Black',
    MONTSERRAT_REGULAR: 'Montserrat-Regular',
    MONTSERRAT_THIN: 'Montserrat-Thin',
};

//================ MARGIN and PADDINGS ===================//

const METRICS = {
    MAR_5: 5,
    MAR_8: 8,
    MAR_9: 9,
    MAR_10: 10,
    MAR_11: 11,
    MAR_12: 12,
    MAR_13: 13,
    MAR_14: 14,
    MAR_15: 15,
    MAR_16: 16,
    MAR_17: 17,
    MAR_18: 18,
    MAR_19: 19,
    MAR_20: 20,
    MAR_21: 21,
    MAR_22: 22,
    MAR_23: 23,
    MAR_24: 24,
    MAR_25: 25,
    MAR_29: 29,
    MAR_30: 30,
    MAR_32: 32,
    MAR_35: 35,
    MAR_40: 40,
    MAR_45: 45,
    MAR_50: 50,
    MAR_55: 55,
    MAR_60: 60,
    MAR_66: 66,
    MAR_81: 81,
    MAR_104: 104,
    MAR_110: 110,
    MAR_120: 120,
    MAR_131: 131,
};

//==================== Define Colors ========================//
const COLORS = {
    GRAY_BACKGROUND: 'rgba(190,190,190,0.5)',
    GRAY: 'gray',
    BORDER_COLOR: '#B4B4B4',
    WHITE: 'white',
    BLACK: 'black',
    RED: '#FF2222',
    GREEN: 'green',
    GRAY_255_6: 'rgba(255,255,255,0.6)',
    GOLD: '#E6C65B',
    LOGINBACKGROUND: '#D8E2EE',
    LOGINTEXT: '#000000',
    TEXTBORDER: '#D7D7D7',
    SHADOW: '#F6F6F6',
    WHITESHADOW: '#FFFFFF',
    LOGINBUTTON: '#F3336B',
    SIGNUP: '#FF0000',
    CHECKBOXBORDER: '#D9D9D9',
    MOBILENUMBER: '#444444',
    BOTTOM_COLOR: '#085DF1',
    INSIDE_COLOR: '#D8E8FC',
    ALERT: '#FF0000',
    ACCEPT: '#2E9909',
    BORDER: '#E2E2E2',
    BLURTEXT: '#828282',
    PROFILEBACK: '#D1D5D7',
    NAMECOLORBORDER: '#F5F5F5',
    TEXTCOLOR: "#DEDEDE",
    BACKGROUND: "#FCF3DE",
    GRAD: ["#D9D9D9","white"],
    GRAD1:["#604536","#EBAA8A","#604536"],

};

//========================= FONT SIZE =========================//
const FONT_SIZES = {
    H1: 24,
    H2: 16,
    H3: 14,
    H4: 12,
    H5: 18,
    H6: 20,
};

export {
    HTTP_CODES,
    FONT_FAMILIES,
    FONT_SIZES,
    URIS,
    COLORS,
    METRICS,
    URI_METHODs,
    STATIC_PAGE,
};