//======================= Screen Names ===================//
const SCREENS = {
    MAIN: 'main',
    TABS: 'tabs',
    ACCOUNT: 'account',
    SPLASH: 'splash',
    LOGIN: 'login',
    FORGET_PASSWORD: 'forgetpassword',
    REGISTER: 'register',
    PRIVACY_POLICY: 'privacy policy',
    DASHBOARD: 'dashboard',
    MOBILENUMBER: 'mobilenumber',
    OTP: 'otp',
    CHAT: 'Dialogs',
    MEETUP: 'meetup',
    WORK: 'work',
    ABOUT: 'about',
    CONDITION: 'condition',
    FAQ: 'faq',
    REFER: 'refer',
    NOTIFICATION: 'notification',
    RATING: 'rating',
    RECENTMEETUP: 'recentmeetup',
    PROFILE: 'profile',
    FORGOTOTP: 'forgototp',
    RECEIVERPROFILE: 'receiverprofile',
    CHATBOX: 'Chatbox',
    RESETPASSWORD: 'Resetpassword',
    WALLET: 'wallet',
    INTERACTION: 'interaction',
    ADDPHOTOS: 'addphotos',
    ONBOARD: 'onboard',
    PERFECTMATCH: 'perfectmatch',
    REGISTERPROFILE:'registerprofile',
    FIRESTORE_CHAT_LIST:'chatlist',
    FIRESTORE_CHAT:'chat',
    RATINGHISTORY: 'ratinghistory',
};

//==================== Validation Messages =================//
const VALIDATE_FORM = {
    FIRST_NAME: 'Please Enter Your Name.',
    LAST_NAME: 'Please enter last name.',
    EMAIL: 'Please enter email address.',
    EMAIL_VALID: 'Please enter valid email address.',
    PASSWORD: 'Please enter password.',
    VALID_PASSWORD: 'Password should be alphanumeric eg. Arsy898',
    VALID_PHONE: 'Please enter valid mobile number.',
    DOB: 'Please enter DOB.',
    SCREEN_NAME: 'Please enter screen name',
    C_PASSWORD: 'Please enter confirm password.',
    MISMATCH: "Password doesn't match",
    LOGOUT: 'Are you sure you want to logout?',
    PRIVACY: 'Please select post privacy.',
    ADDRESS: 'Please enter location',
    GENDER: 'Please select gender.',
    TERMS_AND_CODITION: 'Please Accept Terms & Conditions and Privacy Policy.',
    EMAILMOBILE: 'Please enter username/mobile no.',
    VALIDEMAILMOBILE: 'Please enter valid username/mobile no.',
    VALID_NAME: 'Please enter valid name',
    PHONE: 'Please enter your mobile no.',
    CHECK: 'Please follow our Terms & Conditions',
    CITY: 'Please enter your city',
    VALID_CITY: 'Please enter valid city',
    INTEREST: 'Please enter your Interest',
    PERSONALITY: 'Please enter your Personality',
    OTP: 'Please enter OTP',
    VALID_OTP: 'Please enter valid OTP',
    USER:'Please enter your username',
    VALID_USER:'Please enter valid username eg. Abc_01',
    MESSAGE:'Please enter your message',
    RATING_TEXTFIELD: 'Please enter review',
    RATING_STAR: 'Please select stars',
};

//==================== Pas key =================//
const PAS_KEY = "Rn[6eFr}JM#Dm{Ku*dVyegg[`_LR:Ru5-_`Y7r@)/4_dR!jQxf/8!,};q:d^:jW(r::X' > L3PApAPw / cdeFwYKH=]_dpMwX =*.y@N/3/!pzqsc + SW5ZA.tmzbRug)N";

export {
    SCREENS,
    VALIDATE_FORM,
    PAS_KEY
};